In [1]:
import numpy as np
import matplotlib.pyplot as plt 
np.set_printoptions(precision = 4, suppress=True)
%pylab inline 

Populating the interactive namespace from numpy and matplotlib


In [2]:
np.arange(0.1,5.1,0.1)

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,
        1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,
        2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,
        4.5,  4.6,  4.7,  4.8,  4.9,  5. ])

<img src="http://npac2016.wikispaces.com/file/view/PRank4.png/590255878/PRank4.png" alt="Drawing" style="width: 400px;"/>

In [3]:
#neighbors[i] is the list of pages that i has a link to
neighbors = np.asarray([[1,2],[0,3],[3,0],[2,1,4],[]])

#transfer matrices for first and second prescriptions : 
transfer1, transfer2 = np.zeros((5,5)), np.zeros((5,5))
#number of links per page
links= np.zeros(5)
for i in xrange(5):
    links[i]=len(neighbors[i])

In [4]:
for a in xrange(5):
    for b in neighbors[a]:
        transfer1[b,a] = 1/links[a]
        transfer2[b,a] = 1/links[a]
    if links[a]==0:
        transfer1[b,b]=1
        for b in range(5):
            transfer2[b,a] = 1/4. if b!=a else 0

In [5]:
transfer1

array([[ 0.    ,  0.5   ,  0.5   ,  0.    ,  0.    ],
       [ 0.5   ,  0.    ,  0.    ,  0.3333,  0.    ],
       [ 0.5   ,  0.    ,  0.    ,  0.3333,  0.    ],
       [ 0.    ,  0.5   ,  0.5   ,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.3333,  1.    ]])

In [6]:
#check for normalization of the transfer matrices
print("summing columns")
print([ sum(transfer1[:,j]) for j in range(5)])
print([ sum(transfer2[:,j]) for j in range(5)])

summing columns
[1.0, 1.0, 1.0, 1.0, 1.0]
[1.0, 1.0, 1.0, 1.0, 1.0]


In [7]:
w1, v1 = np.linalg.eig(transfer1)
w2, v2 = np.linalg.eig(transfer2)

In [14]:
print "Eigenvalues of the transfer matrix for the first prescription "
print w1
print "Eigenvalues of the transfer matrix for the second prescription "
print w2

Eigenvalues of the transfer matrix for the first prescription 
[ 1.     -0.9129  0.9129 -0.     -0.    ]
Eigenvalues of the transfer matrix for the second prescription 
[-0.9082  1.     -0.0918  0.      0.    ]


In [15]:
prank1 = v1[:,0]/np.sum(v1[:,0])
print prank1

[ 0.  0.  0.  0.  1.]


In [16]:
prank2 = v2[:,1]/np.sum(v2[:,1])
print prank2

[ 0.24  0.22  0.22  0.24  0.08]


In [17]:
range(1)

[0]

In [18]:
neighbors = [[1,5],[0,5],[0],[0],[0,2],[7],[5],[6,5]]
#damping 
d = 0.85
links= np.zeros(8)
for i in xrange(8):
    links[i]=len(neighbors[i])

In [23]:
#Naive ranking : we rank by links received : 

received = np.zeros(8)
for page in xrange(8):
    for link in neighbors[page]:received[link]+=1
        
print "======================================================"
print "Naive ranking results : top to bottom "
for t in received.argsort()[::-1]:
    print "Page "+str(t+1)+": links received : "+str(received[t])
print "======================================================"

Naive ranking results : top to bottom 
Page 6: links received : 4.0
Page 1: links received : 4.0
Page 8: links received : 1.0
Page 7: links received : 1.0
Page 3: links received : 1.0
Page 2: links received : 1.0
Page 5: links received : 0.0
Page 4: links received : 0.0


In [30]:
transfer = np.zeros((8,8))
for a in xrange(8):
    for b in neighbors[a]:
        transfer[b,a] = 1/links[a]

In [31]:
transfer = d*transfer + (1-d)/8*np.ones(8)

In [32]:
transfer

array([[ 0.0188,  0.4437,  0.8688,  0.8688,  0.4437,  0.0188,  0.0188,
         0.0188],
       [ 0.4437,  0.0188,  0.0188,  0.0188,  0.0188,  0.0188,  0.0188,
         0.0188],
       [ 0.0188,  0.0188,  0.0188,  0.0188,  0.4437,  0.0188,  0.0188,
         0.0188],
       [ 0.0188,  0.0188,  0.0188,  0.0188,  0.0188,  0.0188,  0.0188,
         0.0188],
       [ 0.0188,  0.0188,  0.0188,  0.0188,  0.0188,  0.0188,  0.0188,
         0.0188],
       [ 0.4437,  0.4437,  0.0188,  0.0188,  0.0188,  0.0188,  0.8688,
         0.4437],
       [ 0.0188,  0.0188,  0.0188,  0.0188,  0.0188,  0.0188,  0.0188,
         0.4437],
       [ 0.0188,  0.0188,  0.0188,  0.0188,  0.0188,  0.8688,  0.0188,
         0.0188]])

In [33]:
#check for normalization of the transfer matrices
print("summing columns")
print([ sum(transfer[:,j]) for j in range(8)])

summing columns
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [34]:
w, v = np.linalg.eig(transfer)

In [35]:
print w

[ 1.000+0.j     0.425+0.j    -0.425+0.425j -0.425-0.425j -0.425+0.j
  0.000+0.j    -0.000+0.j    -0.000+0.j   ]


In [36]:
prank = v[:,0]/np.sum(v[:,0])

(0.99999999999999989+0j)